#!/bin/bash
#
# Generate (or regenerate) the files generated by
# autoconf/automake/libtool/etc.
#

set -e # bail out on any error

autoreconf -ifv

# Drop down into libtorrent and run their equivalent script.

(cd libtorrent && ./autotool.sh)

