.\" GeneTorrent man page
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.ie t .ds Tx \s-1T\v'.4n'\h'-.1667'E\v'-.4n'\h'-.125'X\s0
. el  .ds Tx TeX
.de Id
. ds Yr \\$4
. substring Yr 0 3
. ds Mn \\$4
. substring Mn 5 6
. ds Dy \\$4
. substring Dy 8 9
. \" ISO 8601 date, complete format, extended representation
. ds Dt \\*(Yr-\\*(Mn-\\*(Dy
..
.TH GeneTorrent 1 
.hy 0
.
.SH NAME 
GeneTorrent \- transfer genomic data reliably across a network
.SH SYNOPSIS
.B gtupload 
.I manifest-file
.B -c 
.I cred
.B \fR[\fP -p 
.I path
.R ]
.br
.B gtdownload 
.I \fR<\fP URI \fR|\fP UUID \fR|\fP .xml \fR|\fP .gto \fR>\fP
.B -c 
.I cred
.B \fR[\fP -p 
.I path
.RB ] 
.br
.B gtserver 
.I path
.B -q
.I work-queue
.B -c 
.I cred
.B --security-api 
.I signing-URI
.SH DESCRIPTION
.B GeneTorrent
is a file transfer client application designed for the optimal
transfer of genomic data across a computer network.  File transfers
using GeneTorrent are designed to be authenticated, secure, reliable,
and efficient.
.PP
GeneTorrent has 3 operating modes: upload, download, and server.
Upload mode is used to send files to the repository.  Download mode is
used to retrieve files from the repository.  Server mode is used
within the repository to create GeneTorrent server instances that
deliver data to download actors.
.SH OPTIONS
See the man page of each application for usage information.
.SH SEE ALSO
.BR gtdownload(1),
.BR gtserver(1),
.BR gtupload(1).
.SH COPYRIGHT
Copyright \(co
2011-2012
Annai Systems, Inc.
.PP
This is free software;
see the source for copying conditions.
There is NO warranty;
not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

